<a href="https://colab.research.google.com/github/Ebratul/Python/blob/main/pytorch/pytorch(1-3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

Exception in thread Thread-3 (attachment_entry):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/dist-packages/google/colab/_debugpy.py", line 52, in attachment_entry
    debugpy.listen(_dap_port)
  File "/usr/local/lib/python3.11/dist-packages/debugpy/public_api.py", line 31, in wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/debugpy/server/api.py", line 143, in debug
    log.reraise_exception("{0}() failed:", func.__name__, level="info")
  File "/usr/local/lib/python3.11/dist-packages/debugpy/server/api.py", line 141, in debug
    return func(address, settrace_kwargs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/debugpy/server/ap

2.6.0+cu124


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available. Using CPU")

GPU is available
Using GPU: Tesla T4


In [3]:
a = torch.empty(2, 3)

In [4]:
type(a)

torch.Tensor

In [5]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.rand(2,3)

tensor([[0.6277, 0.6537, 0.4197],
        [0.0864, 0.2787, 0.7515]])

In [8]:
torch.manual_seed(100)

In [9]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
print(torch.arange(1, 10, 2))

tensor([1, 3, 5, 7, 9])


In [12]:
torch.linspace(0, 10, 10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [13]:
x = torch.eye(5)
x

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [14]:
torch.full((3,3), 8)

tensor([[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]])

In [15]:
x.shape

torch.Size([5, 5])

In [16]:
torch.empty_like(x)

tensor([[0.0000e+00, 4.3453e-41, 1.8788e+31, 1.7220e+22, 2.1715e-18],
        [1.3385e+22, 5.2944e-08, 1.0578e+21, 1.0739e-05, 3.1948e+21],
        [1.0186e-11, 1.0257e-08, 4.3722e-05, 4.1533e-08, 2.1707e-18],
        [4.5447e+30, 7.0062e+22, 2.1715e-18, 4.5447e+30, 7.0062e+22],
        [2.1707e-18, 1.9284e+31, 3.2314e-18, 9.6635e-06, 8.3189e+20]])

In [17]:
torch.zeros_like(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [18]:
x.dtype

torch.float32

In [19]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [20]:
x.to(torch.int)

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]], dtype=torch.int32)

In [21]:
torch.rand_like(x)

tensor([[0.2627, 0.0428, 0.2080, 0.1180, 0.1217],
        [0.7356, 0.7118, 0.7876, 0.4183, 0.9014],
        [0.9969, 0.7565, 0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770, 0.4440, 0.9478],
        [0.7445, 0.4892, 0.2426, 0.7003, 0.5277]])

In [22]:
d = torch.tensor([1.2, 2.4, 4.5,6.7], dtype=torch.float32)

In [23]:
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.4000, 3.0000, 3.0000])

In [24]:
torch.cuda.is_available()

True

In [25]:
device = torch.device('cuda')

In [26]:
a = torch.rand((2,3), device=device)

In [27]:
b = torch.rand(2, 3)
b

tensor([[0.2472, 0.7909, 0.4235],
        [0.0169, 0.2209, 0.9535]])

In [28]:
b.to(device)

tensor([[0.2472, 0.7909, 0.4235],
        [0.0169, 0.2209, 0.9535]], device='cuda:0')

In [29]:
a+5

tensor([[5.3563, 5.0303, 5.7088],
        [5.2009, 5.0224, 5.9896]], device='cuda:0')

In [30]:
b = torch.rand(4,4)

In [31]:
b

tensor([[0.7064, 0.1629, 0.8902, 0.5163],
        [0.0359, 0.6476, 0.3430, 0.3182],
        [0.5261, 0.0447, 0.5123, 0.9051],
        [0.5989, 0.4450, 0.7278, 0.4563]])

In [32]:
b.reshape(2,2,2,2)

tensor([[[[0.7064, 0.1629],
          [0.8902, 0.5163]],

         [[0.0359, 0.6476],
          [0.3430, 0.3182]]],


        [[[0.5261, 0.0447],
          [0.5123, 0.9051]],

         [[0.5989, 0.4450],
          [0.7278, 0.4563]]]])

In [33]:
b.flatten()

tensor([0.7064, 0.1629, 0.8902, 0.5163, 0.0359, 0.6476, 0.3430, 0.3182, 0.5261,
        0.0447, 0.5123, 0.9051, 0.5989, 0.4450, 0.7278, 0.4563])

In [34]:
c = torch.rand(2,3,4)

In [35]:
c

tensor([[[0.3389, 0.6211, 0.5530, 0.6896],
         [0.3687, 0.9053, 0.8356, 0.3039],
         [0.6726, 0.5740, 0.9233, 0.9178]],

        [[0.7590, 0.7775, 0.6179, 0.3379],
         [0.2170, 0.9454, 0.7116, 0.1157],
         [0.6574, 0.3451, 0.0453, 0.9798]]])

In [36]:
c.permute(2,0,1) #(4,2,3)

tensor([[[0.3389, 0.3687, 0.6726],
         [0.7590, 0.2170, 0.6574]],

        [[0.6211, 0.9053, 0.5740],
         [0.7775, 0.9454, 0.3451]],

        [[0.5530, 0.8356, 0.9233],
         [0.6179, 0.7116, 0.0453]],

        [[0.6896, 0.3039, 0.9178],
         [0.3379, 0.1157, 0.9798]]])

In [37]:
c.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [38]:
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [39]:
def dy_dx(x):
  return 2*x

In [40]:
dy_dx(3)

6

In [41]:
import torch

In [42]:
x = torch.tensor(3.0, requires_grad=True)

In [43]:
y = x**2

In [44]:
x

tensor(3., requires_grad=True)

In [45]:
y

tensor(9., grad_fn=<PowBackward0>)

In [46]:
y.backward()

In [47]:
x.grad

tensor(6.)

In [48]:
import math

In [49]:
def dz_dx(x):
  return 2*x*math.cos(x**2)

In [50]:
dz_dx(4)

-7.661275842587077

In [51]:
x = torch.tensor(4.0, requires_grad=True)

In [52]:
y=x**2

In [53]:
z = torch.sin(y)

In [54]:
z.backward()

In [55]:
x

tensor(4., requires_grad=True)

In [56]:
y

tensor(16., grad_fn=<PowBackward0>)

In [57]:
z

tensor(-0.2879, grad_fn=<SinBackward0>)

In [58]:
x.grad

tensor(-7.6613)

In [59]:
y.grad

/tmp/ipython-input-59-486760323.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  y.grad


In [60]:
import torch

x = torch.tensor(6.7)
y = torch.tensor(0.0)

w = torch.tensor(1.0)
b = torch.tensor(0.0)

In [61]:
def binary_cross_entroy_loss(prediction, target):
  epsilon = 1e-8
  prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
  return -(target*torch.log(prediction) + (1-target)*torch.log(1-prediction))

In [62]:
z = w*x + b
y_pred = torch.sigmoid(z)
loss = binary_cross_entroy_loss(y_pred, y)

In [63]:
loss

tensor(6.7012)

In [64]:
dloss_dy_pred = (y_pred - y)/(y_pred*(1-y_pred))
dy_pred_dz = y_pred*(1-y_pred)

dz_dw = x
dz_db = 1

dL_dw = dloss_dy_pred*dy_pred_dz*dz_dw
dL_db = dloss_dy_pred*dy_pred_dz*dz_db

In [65]:
print(f"dL_dw: {dL_dw}")
print(f"dL_db: {dL_db}")

dL_dw: 6.691762447357178
dL_db: 0.998770534992218


In [66]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

In [67]:
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [68]:
w

tensor(1., requires_grad=True)

In [69]:
b

tensor(0., requires_grad=True)

In [70]:
z = w*x +b

In [71]:
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [72]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [73]:
loss = binary_cross_entroy_loss(y_pred, y)

In [74]:
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [75]:
loss.backward()

In [76]:
w.grad

tensor(6.6918)

In [77]:
b.grad

tensor(0.9988)

In [78]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)

In [79]:
x

tensor([1., 2., 3.], requires_grad=True)

In [80]:
y = (x**2).mean()

In [81]:
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [82]:
y.backward()

In [83]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [84]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [85]:
y = x**2
y

tensor(4., grad_fn=<PowBackward0>)

In [86]:
y.backward()

In [87]:
x.grad

tensor(4.)

In [88]:
x.grad.zero_()

tensor(0.)

In [89]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [90]:
y = x**2
y

tensor(4., grad_fn=<PowBackward0>)

In [91]:
y.backward()

In [92]:
x.grad

tensor(4.)

In [93]:
# option 1 - requires_grad_(False)
# option 2 - detach()
# option 3 - torch.no_grad()

In [94]:
x.requires_grad_(False)

tensor(2.)

In [95]:
y = x**2

In [96]:
y

tensor(4.)

In [97]:
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [98]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [99]:
z = x.detach()
z

tensor(2.)

In [100]:
y = x**2

In [101]:
y

tensor(4., grad_fn=<PowBackward0>)

In [102]:
y1 = z**2
y

tensor(4., grad_fn=<PowBackward0>)

In [103]:
y.backward()

In [104]:
y1.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [105]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [106]:
y = x**2

In [107]:
y

tensor(4., grad_fn=<PowBackward0>)

In [108]:
y.backward()

In [109]:
torch.rand(32,1, dtype = torch.float64)

tensor([[0.6420],
        [0.6170],
        [0.6956],
        [0.9143],
        [0.9448],
        [0.4672],
        [0.9024],
        [0.6923],
        [0.0995],
        [0.3475],
        [0.9084],
        [0.8875],
        [0.0126],
        [0.7926],
        [0.2831],
        [0.9545],
        [0.1373],
        [0.8079],
        [0.8707],
        [0.2275],
        [0.1472],
        [0.6706],
        [0.8562],
        [0.6205],
        [0.3477],
        [0.7113],
        [0.7878],
        [0.0238],
        [0.3487],
        [0.8848],
        [0.5421],
        [0.2808]], dtype=torch.float64)

In [110]:
torch.rand(1, dtype = torch.float64)

tensor([0.2497], dtype=torch.float64)

In [116]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [114]:
with torch.no_grad():
  y = x**2
  # y.backward()
  print(x.grad)


None
