<a href="https://colab.research.google.com/github/Ebratul/Python/blob/main/DL/Embedding_RNN_Sentiment_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from keras.layers import Dense, SimpleRNN
from keras.models import Sequential

In [2]:
model = Sequential()

model.add(SimpleRNN(3, input_shape = (4,5)))
model.add(Dense(1, activation='sigmoid'))

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 3)              │            27 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31 (124.00 B)

 Trainable params: 31 (124.00 B)

 Non-trainable params: 0 (0.00 B)

In [3]:
print(model.get_weights()[0].shape)
model.get_weights()[0]

(5, 3)


array([[ 0.6337758 , -0.20225596, -0.29884732],
       [ 0.30001456,  0.30062753, -0.23722875],
       [-0.26861155,  0.5301241 , -0.60309446],
       [-0.01792544, -0.5028373 ,  0.23153847],
       [-0.5256391 , -0.7723317 ,  0.436809  ]], dtype=float32)

In [4]:
print(model.get_weights()[1].shape)
model.get_weights()[1]

(3, 3)


array([[-0.76043105,  0.6088647 ,  0.2258944 ],
       [ 0.64934427,  0.7181261 ,  0.25029358],
       [-0.00982573,  0.33701426, -0.9414483 ]], dtype=float32)

In [5]:
print(model.get_weights()[2].shape)
model.get_weights()[2]

(3,)


array([0., 0., 0.], dtype=float32)

In [6]:
print(model.get_weights()[3].shape)
model.get_weights()[3]

(3, 1)


array([[ 1.0773345 ],
       [ 0.97679436],
       [-0.35335827]], dtype=float32)

In [7]:
print(model.get_weights()[4].shape)
model.get_weights()[4]

(1,)


array([0.], dtype=float32)

In [8]:
import numpy as np

In [9]:
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [10]:
pip install tensorflow


In [11]:
from tensorflow.keras.preprocessing.text import Tokenizer


In [12]:
tokenizer = Tokenizer(oov_token='<onthing>')

In [13]:
tokenizer.fit_on_texts(docs)

In [14]:
tokenizer.word_index

{'<onthing>': 1,
 'india': 2,
 'jeetega': 3,
 'hip': 4,
 'ki': 5,
 'jai': 6,
 'kohli': 7,
 'sachin': 8,
 'dhoni': 9,
 'go': 10,
 'hurray': 11,
 'bhai': 12,
 'bharat': 13,
 'mata': 14,
 'modi': 15,
 'ji': 16,
 'inquilab': 17,
 'zindabad': 18}

In [15]:
tokenizer.word_counts

OrderedDict([('go', 1),
             ('india', 4),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 3),
             ('bhai', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 2),
             ('jai', 2),
             ('kohli', 2),
             ('sachin', 2),
             ('dhoni', 2),
             ('modi', 1),
             ('ji', 1),
             ('inquilab', 1),
             ('zindabad', 1)])

In [16]:
tokenizer.document_count

10

In [17]:
sequence = tokenizer.texts_to_sequences(docs)
sequence

[[10, 2],
 [2, 2],
 [4, 4, 11],
 [3, 12, 3, 2, 3],
 [13, 14, 5, 6],
 [7, 7],
 [8, 8],
 [9, 9],
 [15, 16, 5, 6],
 [17, 18]]

In [18]:
from keras.utils import pad_sequences

sequence = pad_sequences(sequence, padding='post')
sequence

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 11,  0,  0],
       [ 3, 12,  3,  2,  3],
       [13, 14,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [15, 16,  5,  6,  0],
       [17, 18,  0,  0,  0]], dtype=int32)

In [19]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten

In [20]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [21]:
len(X_train[0])

218

In [22]:
X_train = pad_sequences(X_train, padding = 'post', maxlen = 50)
X_test = pad_sequences(X_test, padding='post', maxlen=50)

In [23]:
model = Sequential()

model.add(SimpleRNN(32, input_shape = (50, 1), return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)        │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [24]:
model.compile(loss = 'binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train, epochs = 10,  validation_data=(X_test, y_test))

Epoch 1/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 18s 20ms/step - accuracy: 0.5000 - loss: 0.6951 - val_accuracy: 0.5029 - val_loss: 0.6936
Epoch 2/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 15s 13ms/step - accuracy: 0.5116 - loss: 0.6929 - val_accuracy: 0.5064 - val_loss: 0.6943
Epoch 3/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 9s 12ms/step - accuracy: 0.5119 - loss: 0.6928 - val_accuracy: 0.5106 - val_loss: 0.6934
Epoch 4/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 13ms/step - accuracy: 0.5087 - loss: 0.6932 - val_accuracy: 0.5023 - val_loss: 0.6945
Epoch 5/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - accuracy: 0.5027 - loss: 0.6936 - val_accuracy: 0.4999 - val_loss: 0.6942
Epoch 6/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - accuracy: 0.5121 - loss: 0.6928 - val_accuracy: 0.5021 - val_loss: 0.6949
Epoch 7/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - accuracy: 0.5063 - loss: 0.6928 - val_accuracy: 0.5049 - val_loss: 0.6950
Epoch 8/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 12s 15ms/step - accuracy: 0.5087 - loss: 0.6924 - v

# Embedding

In [25]:
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [26]:
from tensorflow.keras.preprocessing.text import  Tokenizer
tokenizer = Tokenizer()

In [27]:
tokenizer.fit_on_texts(docs)

In [28]:
len(tokenizer.word_index)

17

In [29]:
sequence = tokenizer.texts_to_sequences(docs)
sequence

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [30]:
from keras.utils import pad_sequences

sequence = pad_sequences(sequence, padding='post')
len(sequence)

10

In [31]:
model = Sequential()
model.add(Embedding(17,output_dim=2,input_length=10))

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [32]:
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Embedding, Input

# model = Sequential([
#     Input(shape=(5,)),
#     Embedding(input_dim=17, output_dim=2)
# ])

# model.summary()

In [46]:
vocab_size = len(tokenizer.word_index) + 1
sequence_length = sequence.shape[1]
sequence_length

5

In [35]:
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=2, input_length=sequence_length))

model.build(input_shape=(None, 5))  # 👈 important

model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 5, 2)           │            36 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 36 (144.00 B)

 Trainable params: 36 (144.00 B)

 Non-trainable params: 0 (0.00 B)

In [36]:
model.compile(optimizer='adam', loss='mse')

In [38]:

output = model.predict(sequence)
print(output)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step
[[[-0.04538672  0.0122697 ]
  [-0.01850574  0.04496807]
  [-0.00111371 -0.02107175]
  [-0.00111371 -0.02107175]
  [-0.00111371 -0.02107175]]

 [[-0.01850574  0.04496807]
  [-0.01850574  0.04496807]
  [-0.00111371 -0.02107175]
  [-0.00111371 -0.02107175]
  [-0.00111371 -0.02107175]]

 [[-0.0060133   0.03462939]
  [-0.0060133   0.03462939]
  [-0.0148384  -0.0239773 ]
  [-0.00111371 -0.02107175]
  [-0.00111371 -0.02107175]]

 [[ 0.02697095 -0.04909594]
  [-0.0215512   0.00442729]
  [ 0.02697095 -0.04909594]
  [-0.01850574  0.04496807]
  [ 0.02697095 -0.04909594]]

 [[-0.01860706  0.01922332]
  [ 0.01431303  0.02442614]
  [ 0.02983623 -0.00339919]
  [-0.03552772 -0.01235999]
  [-0.00111371 -0.02107175]]

 [[-0.01842762  0.02377535]
  [-0.01842762  0.02377535]
  [-0.00111371 -0.02107175]
  [-0.00111371 -0.02107175]
  [-0.00111371 -0.02107175]]

 [[ 0.03231793  0.02063476]
  [ 0.03231793  0.02063476]
  [-0.00111371 -0.02107175]
  [-0.00111371 -0.0210717

In [39]:
from keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense, SimpleRNN,Embedding, Flatten

In [55]:
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=10000)

In [58]:
maxlen = 50
X_train = pad_sequences(X_train, padding='post', maxlen=maxlen)
X_test = pad_sequences(X_test, padding='post', maxlen=maxlen)

In [59]:
X_train.shape

(25000, 50)

In [60]:
print("Max index in train:", X_train.max())

Max index in train: 9999


In [61]:
print("Max index in X_train:", X_train.max())
print("Embedding input_dim:", vocab_size)

Max index in X_train: 9999
Embedding input_dim: 18


In [64]:
# ---------------- Model ----------------
model = Sequential()

model.add(Embedding(input_dim=10000, output_dim=2, input_length=maxlen))
model.add(SimpleRNN(32, return_sequences=False))
model.add(Dense(1, activation='sigmoid'))
model.build(input_shape=(None, 50))

model.summary()

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_9 (Embedding)         │ (None, 50, 2)          │        20,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_8 (SimpleRNN)        │ (None, 32)             │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21,153 (82.63 KB)

 Trainable params: 21,153 (82.63 KB)

 Non-trainable params: 0 (0.00 B)

In [65]:
model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [66]:
history = model.fit(
    X_train, y_train,
    epochs=5,
    validation_data=(X_test, y_test)
)

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 15s 16ms/step - accuracy: 0.5422 - loss: 0.6695 - val_accuracy: 0.7950 - val_loss: 0.4458
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 13s 16ms/step - accuracy: 0.8338 - loss: 0.3876 - val_accuracy: 0.8122 - val_loss: 0.4160
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 13s 16ms/step - accuracy: 0.8730 - loss: 0.3153 - val_accuracy: 0.8061 - val_loss: 0.4482
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 13s 16ms/step - accuracy: 0.8902 - loss: 0.2820 - val_accuracy: 0.8048 - val_loss: 0.4443
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - accuracy: 0.9082 - loss: 0.2498 - val_accuracy: 0.7973 - val_loss: 0.4541
