<a href="https://colab.research.google.com/github/Ebratul/Python/blob/main/DL/Embedding_RNN_Sentiment_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from keras.layers import Dense, SimpleRNN
from keras.models import Sequential

In [2]:
model = Sequential()

model.add(SimpleRNN(3, input_shape = (4,5)))
model.add(Dense(1, activation='sigmoid'))

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 3)              │            27 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31 (124.00 B)

 Trainable params: 31 (124.00 B)

 Non-trainable params: 0 (0.00 B)

In [3]:
print(model.get_weights()[0].shape)
model.get_weights()[0]

(5, 3)


array([[ 0.774033  ,  0.7603201 ,  0.5059572 ],
       [-0.1637485 ,  0.50687724,  0.45419222],
       [ 0.11339384,  0.62833375, -0.43158305],
       [ 0.6157604 ,  0.5584695 ,  0.516365  ],
       [-0.02310574,  0.6054495 , -0.5060804 ]], dtype=float32)

In [4]:
print(model.get_weights()[1].shape)
model.get_weights()[1]

(3, 3)


array([[ 0.5991527 ,  0.7219917 ,  0.3460406 ],
       [ 0.47472483, -0.66839856,  0.5726078 ],
       [ 0.64471114, -0.17880544, -0.74322015]], dtype=float32)

In [5]:
print(model.get_weights()[2].shape)
model.get_weights()[2]

(3,)


array([0., 0., 0.], dtype=float32)

In [6]:
print(model.get_weights()[3].shape)
model.get_weights()[3]

(3, 1)


array([[-0.55724424],
       [ 1.1389896 ],
       [-0.2589742 ]], dtype=float32)

In [7]:
print(model.get_weights()[4].shape)
model.get_weights()[4]

(1,)


array([0.], dtype=float32)

In [8]:
import numpy as np

In [9]:
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [10]:
pip install tensorflow


In [11]:
from tensorflow.keras.preprocessing.text import Tokenizer


In [12]:
tokenizer = Tokenizer(oov_token='<onthing>')

In [13]:
tokenizer.fit_on_texts(docs)

In [14]:
tokenizer.word_index

{'<onthing>': 1,
 'india': 2,
 'jeetega': 3,
 'hip': 4,
 'ki': 5,
 'jai': 6,
 'kohli': 7,
 'sachin': 8,
 'dhoni': 9,
 'go': 10,
 'hurray': 11,
 'bhai': 12,
 'bharat': 13,
 'mata': 14,
 'modi': 15,
 'ji': 16,
 'inquilab': 17,
 'zindabad': 18}

In [15]:
tokenizer.word_counts

OrderedDict([('go', 1),
             ('india', 4),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 3),
             ('bhai', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 2),
             ('jai', 2),
             ('kohli', 2),
             ('sachin', 2),
             ('dhoni', 2),
             ('modi', 1),
             ('ji', 1),
             ('inquilab', 1),
             ('zindabad', 1)])

In [16]:
tokenizer.document_count

10

In [17]:
sequence = tokenizer.texts_to_sequences(docs)
sequence

[[10, 2],
 [2, 2],
 [4, 4, 11],
 [3, 12, 3, 2, 3],
 [13, 14, 5, 6],
 [7, 7],
 [8, 8],
 [9, 9],
 [15, 16, 5, 6],
 [17, 18]]

In [18]:
from keras.utils import pad_sequences

sequence = pad_sequences(sequence, padding='post')
sequence

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 11,  0,  0],
       [ 3, 12,  3,  2,  3],
       [13, 14,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [15, 16,  5,  6,  0],
       [17, 18,  0,  0,  0]], dtype=int32)

In [19]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten

In [20]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [21]:
len(X_train[0])

218

In [22]:
X_train = pad_sequences(X_train, padding = 'post', maxlen = 50)
X_test = pad_sequences(X_test, padding='post', maxlen=50)

In [23]:
model = Sequential()

model.add(SimpleRNN(32, input_shape = (50, 1), return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)        │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [24]:
model.compile(loss = 'binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train, epochs = 10,  validation_data=(X_test, y_test))

Epoch 1/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 14s 16ms/step - accuracy: 0.5027 - loss: 0.6959 - val_accuracy: 0.5050 - val_loss: 0.6941
Epoch 2/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 14s 17ms/step - accuracy: 0.5082 - loss: 0.6934 - val_accuracy: 0.5044 - val_loss: 0.6942
Epoch 3/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 18s 14ms/step - accuracy: 0.5050 - loss: 0.6931 - val_accuracy: 0.5012 - val_loss: 0.6966
Epoch 4/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 10s 13ms/step - accuracy: 0.5138 - loss: 0.6924 - val_accuracy: 0.5003 - val_loss: 0.6961
Epoch 5/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 14s 17ms/step - accuracy: 0.5092 - loss: 0.6927 - val_accuracy: 0.5040 - val_loss: 0.6935
Epoch 6/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 12s 15ms/step - accuracy: 0.5098 - loss: 0.6922 - val_accuracy: 0.5028 - val_loss: 0.6942
Epoch 7/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - accuracy: 0.5037 - loss: 0.6922 - val_accuracy: 0.5062 - val_loss: 0.6947
Epoch 8/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 20s 14ms/step - accuracy: 0.5120 - loss: 0.6923 - 

# Embedding

In [25]:
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [26]:
from tensorflow.keras.preprocessing.text import  Tokenizer
tokenizer = Tokenizer()

In [27]:
tokenizer.fit_on_texts(docs)

In [28]:
len(tokenizer.word_index)

17

In [29]:
sequence = tokenizer.texts_to_sequences(docs)
sequence

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [30]:
from keras.utils import pad_sequences

sequence = pad_sequences(sequence, padding='post')
len(sequence)

10

In [31]:
model = Sequential()
model.add(Embedding(17,output_dim=2,input_shape=(10,)))

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 10, 2)          │            34 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 34 (136.00 B)

 Trainable params: 34 (136.00 B)

 Non-trainable params: 0 (0.00 B)

In [32]:
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Embedding, Input

# model = Sequential([
#     Input(shape=(5,)),
#     Embedding(input_dim=17, output_dim=2)
# ])

# model.summary()

In [33]:
vocab_size = len(tokenizer.word_index) + 1
sequence_length = sequence.shape[1]
sequence_length

5

In [34]:
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=2, input_length=sequence_length))

model.build(input_shape=(None, 5))  # 👈 important

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 5, 2)           │            36 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 36 (144.00 B)

 Trainable params: 36 (144.00 B)

 Non-trainable params: 0 (0.00 B)

In [35]:
model.compile(optimizer='adam', loss='mse')

In [36]:

output = model.predict(sequence)
print(output)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step
[[[-0.00886047  0.04306405]
  [-0.01674259  0.03457854]
  [-0.01492085  0.01210613]
  [-0.01492085  0.01210613]
  [-0.01492085  0.01210613]]

 [[-0.01674259  0.03457854]
  [-0.01674259  0.03457854]
  [-0.01492085  0.01210613]
  [-0.01492085  0.01210613]
  [-0.01492085  0.01210613]]

 [[ 0.01545615 -0.00609393]
  [ 0.01545615 -0.00609393]
  [ 0.04373643  0.02127424]
  [-0.01492085  0.01210613]
  [-0.01492085  0.01210613]]

 [[ 0.02466866  0.02334804]
  [ 0.00691376  0.01488571]
  [ 0.02466866  0.02334804]
  [-0.01674259  0.03457854]
  [ 0.02466866  0.02334804]]

 [[ 0.02221778  0.01336323]
  [-0.0170604  -0.04033455]
  [ 0.02387946 -0.01841228]
  [-0.00089531  0.04277574]
  [-0.01492085  0.01210613]]

 [[-0.00410733  0.02390045]
  [-0.00410733  0.02390045]
  [-0.01492085  0.01210613]
  [-0.01492085  0.01210613]
  [-0.01492085  0.01210613]]

 [[-0.00049625 -0.02250738]
  [-0.00049625 -0.02250738]
  [-0.01492085  0.01210613]
  [-0.01492085  0.0121061

In [37]:
from keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense, SimpleRNN,Embedding, Flatten

In [38]:
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=10000)

In [39]:
maxlen = 50
X_train = pad_sequences(X_train, padding='post', maxlen=maxlen)
X_test = pad_sequences(X_test, padding='post', maxlen=maxlen)

In [40]:
X_train.shape

(25000, 50)

In [41]:
print("Max index in train:", X_train.max())

Max index in train: 9999


In [42]:
print("Max index in X_train:", X_train.max())
print("Embedding input_dim:", vocab_size)

Max index in X_train: 9999
Embedding input_dim: 18


In [43]:
# ---------------- Model ----------------
model = Sequential()

model.add(Embedding(input_dim=10000, output_dim=2, input_length=maxlen))
model.add(SimpleRNN(32, return_sequences=False))
model.add(Dense(1, activation='sigmoid'))
model.build(input_shape=(None, 50))

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 50, 2)          │        20,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_2 (SimpleRNN)        │ (None, 32)             │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21,153 (82.63 KB)

 Trainable params: 21,153 (82.63 KB)

 Non-trainable params: 0 (0.00 B)

In [44]:
model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [45]:
history = model.fit(
    X_train, y_train,
    epochs=5,
    validation_data=(X_test, y_test)
)

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 15s 17ms/step - accuracy: 0.5171 - loss: 0.6875 - val_accuracy: 0.7500 - val_loss: 0.5120
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 13s 17ms/step - accuracy: 0.7933 - loss: 0.4520 - val_accuracy: 0.7994 - val_loss: 0.4407
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 13s 17ms/step - accuracy: 0.8609 - loss: 0.3354 - val_accuracy: 0.8028 - val_loss: 0.4322
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 15s 20ms/step - accuracy: 0.8961 - loss: 0.2696 - val_accuracy: 0.7977 - val_loss: 0.4789
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 18s 17ms/step - accuracy: 0.9168 - loss: 0.2264 - val_accuracy: 0.7908 - val_loss: 0.5077
